import { z } from "@hono/zod-openapi";
import { paginated, PaginationQuerySchema } from "../CommonSchema.ts";

export const ReportType = z.enum(["TEST_SCENARIO", "CODE_GENERATION", "MASTER_PLAN"])
    .describe("The type of the report.")
    .openapi({ example: "TEST_SCENARIO" });

const StepStatus = z.enum(["SUCCESS", "FAILED"])
    .openapi({ example: "SUCCESS" });

const StepResultSchema = z.object({
    stepIndex: z.number().int()
        .describe("Order of the step in the sequence.")
        .openapi({ example: 1 }),
    stepDescription: z.string()
        .describe("Explanation of what this step does.")
        .openapi({ example: "Fetch user profile from API" }),
    scriptContent: z.string()
        .describe("The actual JavaScript code executed in Docker.")
        .openapi({ example: "const res = await fetch('...');" }),
    status: StepStatus,
    logs: z.string()
        .describe("Captured STDOUT and STDERR from the Docker container.")
        .openapi({ example: "STDOUT:\nRequest sent...\nSTDERR:\n" }),
    error: z.string().optional()
        .describe("Error message if the step failed (JSON stringified)."),
    contextAfter: z.any().optional()
        .describe("State of the context object after execution.")
        .openapi({ type: "object" }),
    relatedKnowledge: z.array(z.any()).optional()
        .describe("Relevant documents from VectorDB if step failed."),
});

const DetailedResultsSchema = z.object({
    executionPlan: z.any().optional()
        .describe("The original JSON plan or code generated by the LLM.")
        .openapi({ type: "object" }),
    initialContext: z.string().optional()
        .describe("The initial state context provided to the test."),
    steps: z.array(StepResultSchema).optional()
        .describe("List of executed steps or generated code examples and their results."),
    durationMs: z.number().optional()
        .describe("Total execution time in milliseconds."),
    finalOutput: z.string().optional()
        .describe("Final Markdown output for code generation mode."),
});

const ReportId = z.string()
    .describe("Unique ID of the report.")
    .openapi({ example: "rep-d9a7f1" });

const TestSuiteId = z.string().optional()
    .describe("The ID of the test suite that generated this report (optional for MASTER_PLAN).")
    .openapi({ example: "ts-8f3b2e" });

const ReportStatus = z.enum(["PENDING", "RUNNING", "SUCCESS", "FAILED", "PARTIAL_FAILURE"])
    .describe("Current status of the test run.")
    .openapi({ example: "SUCCESS" });

const ReportSummary = z.string().optional()
    .describe("A brief summary of the results (e.g. 'Failed at step 3').")
    .openapi({ example: "Successfully executed 5 steps." });

const CreatedAt = z.string().datetime()
    .describe("Timestamp of creation.")
    .openapi({ example: "2025-10-27T11:00:00Z" });

const ProjectId = z.string()
    .describe("The ID of the project.")
    .openapi({ example: "proj-a4c1d" });

export const ReportSchema = z.object({
    id: ReportId,
    testSuiteId: TestSuiteId,
    projectId: ProjectId,
    status: ReportStatus,
    type: ReportType.default("TEST_SCENARIO"),
    summary: ReportSummary,
    initialContext: z.string().describe("Initial context"),
    executionPlan: z.any().describe("Execution plan"),
    steps: z.array(StepResultSchema).describe("Execution steps"),
    durationMs: z.number().optional().describe("Duration in ms"),
    detailedResults: DetailedResultsSchema.optional(),
    masterPlanGoals: z.array(z.string()).optional(),
    masterPlanId: z.string().optional(),
    masterPlanReports: z.array(z.string()).optional(),
    structuredSummary: z.any().optional(),
    createdAt: CreatedAt,
}).openapi("Report");

export const ReportIdParam = z.object({
    reportId: ReportId.describe("The unique ID of the Report for URL path."),
});

export const ListReportItemSchema = z.object({
    id: ReportId,
    testSuiteId: TestSuiteId,
    status: ReportStatus,
    type: ReportType.optional(),
    createdAt: CreatedAt,
    masterPlanId: z.string().optional(),
    masterPlanGoals: z.array(z.string()).optional(),
    structuredSummary: z.any().optional(),
});

export const ListReportSchema = z.array(ListReportItemSchema);

export const ReportListQuerySchema = PaginationQuerySchema.extend({
    projectId: z.string().optional().openapi({
        param: { name: "projectId", in: "query" },
        description: "Filter reports by the project they belong to.",
    }),
    testSuiteId: z.string().optional().openapi({
        param: { name: "testSuiteId", in: "query" },
        description: "Filter reports by the test suite that produced them.",
    }),
    status: ReportStatus.optional().openapi({
        param: { name: "status", in: "query" },
        description: "Filter by run status.",
    }),
    type: ReportType.optional().openapi({
        param: { name: "type", in: "query" },
        description: "Filter by report type.",
    }),
});

export const PaginatedReportListSchema = paginated(ListReportItemSchema).openapi("PaginatedReports");

export type ReportType = z.infer<typeof ReportType>;
export type Report = z.infer<typeof ReportSchema>;
export type ReportDetailedResults = z.infer<typeof DetailedResultsSchema>;
export type ReportStepResult = z.infer<typeof StepResultSchema>;
export type ReportIdParam = z.infer<typeof ReportIdParam>;
export type ListReportSchema = z.infer<typeof ListReportSchema>;
